version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: quiz
    environment:
      MYSQL_ROOT_PASSWORD: quiz
      MYSQL_DATABASE: quiz
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

volumes:
  db_data: