---
- name: Instalar NGINX e fazer deploy da pasta web do repositório
  hosts: webservers
  become: true

  tasks:
    - name: Atualizar cache de pacotes
      apt:
        update_cache: yes

    - name: Instalar NGINX
      apt:
        name: nginx
        state: present

    - name: Iniciar e habilitar NGINX
      service:
        name: nginx
        state: started
        enabled: true

    - name: Instalar Git
      apt:
        name: git
        state: present

    - name: Clonar repositório com código web
      git:
        repo: https://github.com/BrunoSantos88/chellenge-golang-quiz
        dest: /opt/chellenge-golang-quiz
        version: main
        force: yes

    - name: Garantir que /var/www/html existe
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Mover conteúdo da pasta web para /var/www/html
      shell: mv /opt/chellenge-golang-quiz/web/* /var/www/html/
      args:
        removes: /opt/chellenge-golang-quiz/web/*
